### PR TITLE
LPS-120445 Remove data-testid and update tests

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/naraandrade/liferay-portal/pull/46. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/8fe40881299f~1...8fe40881299f)

**Comment by albinojunior** [comment]
ci:forward

**Pull request closed without merging**
