### PR TITLE
LPS-104318 buildLang

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/982.

**Pull request closed without merging**
