### PR TITLE
LPS-119399 buildLang

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
ci:test:sf

**Pull request closed without merging**
