### PR TITLE
LPS-104318 | LPS-104854 Fixing poshi paths

### PR DESCRIPTION
**Pull request by barrosdennys**

### CODE REVIEW

**Comment by barrosdennys** [comment]
ci:test:workflow

**Comment by barrosdennys** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/gabrielpramos/liferay-portal/pull/21.

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/313.

**Pull request closed without merging**
