### PR TITLE
LPS-111680 Rename

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
@albinojunior vamos conversar amanhã sobre algumas mudanças que julgo necessárias.

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/264. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/2c88bb58a0a5~1...2c88bb58a0a5)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/268. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/6768fa69e5ea~9...6768fa69e5ea)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/albinojunior/liferay-portal/pull/94. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/f58c6bcf3380~10...f58c6bcf3380)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/albinojunior/liferay-portal/pull/95. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/0a16ef039b7c~10...0a16ef039b7c)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/albinojunior/liferay-portal/pull/96. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/874f51b2055e~10...874f51b2055e)

**Pull request closed without merging**
