### PR TITLE
LPS-107622 Regen

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/356. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/f7f3c6c5d361~1...f7f3c6c5d361)

**Pull request closed without merging**
