### PR TITLE
LPS-107147 Regen

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/353. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/555cd544367e~1...555cd544367e)

**Pull request closed without merging**
