### PR TITLE
LPS-119686 Fix deploy button disabled validation function

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
ci:stop

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/albinojunior/liferay-portal/pull/177. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/f75d142cd720~1...f75d142cd720)

**Pull request closed without merging**
