### PR TITLE
LPS-106219 | LPS-108676 Add parameter instanceIds to AssigneeUserBulkSelection

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/470. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/921854673d0b~6...921854673d0b)

**Pull request closed without merging**
