### PR TITLE
LPS-106219 | LPS-108676 Regen

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/475. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/7ffb52b1cfc3~6...7ffb52b1cfc3)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/479. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/01d7e8fed503~6...01d7e8fed503)

**Pull request closed without merging**
