### PR TITLE
LPS-110883 Create and update tests

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/gabrielpramos/liferay-portal/pull/51. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/ce1ba57bec31~1...ce1ba57bec31)

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/gabrielpramos/liferay-portal/pull/53. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/ac06a7dfb2b6~5...ac06a7dfb2b6)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/gabrielpramos/liferay-portal/pull/57. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/927dbba281e0~5...927dbba281e0)

**Comment by albinojunior** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/536. [See changes here.](https://github.com/albinojunior/liferay-portal/compare/8212db814a96~5...8212db814a96)

**Pull request closed without merging**
